DECLARE
 V_FNAME EMPLOYEE.FNAME%TYPE;
 V_INNAME EMPLOYEE.INNAME%TYPE;
 V_SALARY EMPLOYEE.SALARY%TYPE;
BEGIN
 SELECT FNAME,INNAME,SALARY INTO V_FNAME,V_INNAME,V_SALARY  FROM EMPLOYEE WHERE SSN=2;
 dbms_output.put_line('FNAME'||' '||'INNANE'||' '||'SALARY');
 DBMS_OUTPUT.PUT_LINE(V_FNAME||' '||V_INNAME||' '||V_SALARY);
 END;
/